# Generated by Django 2.1 on 2018-12-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NuomiMovie',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('daoyan', models.CharField(blank=True, max_length=200, null=True)),
                ('zhuyao', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('republish_date', models.CharField(blank=True, max_length=200, null=True)),
                ('runtime', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nuomi_movie',
                'managed': False,
            },
        ),
    ]
